In [1]:
import pandas as pd
import numpy as np

In [4]:
import os

print(os.getcwd())

d:\COE PROJECT\spare_parts_analogue_selector\src

In [7]:
import os

print(os.listdir(r"D:\COE PROJECT\spare_parts_analogue_selector\data"))

['failures.csv.txt', 'launch_curves.csv.txt', 'products.csv.txt', 'promotions.csv.txt']

In [9]:
products = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\products.csv.txt")
products.head()

  product_id   category  engine_power_kw  weight_kg  price_usd  launch_month
0       P001  Excavator              100       5000      50000             1
1       P002  Excavator              110       5200      53000             2
2       P003  Excavator              105       5100      51500             3
3       P004  Excavator              120       5500      58000             2
4       P005  Excavator               95       4800      47000             1

In [12]:
products = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\failures.csv.txt")
products.head()

  product_id  avg_failure_rate  critical_failures common_spare_part
0       P001              0.12                  8    Hydraulic Pump
1       P002              0.14                  9    Hydraulic Pump
2       P003              0.13                  8    Hydraulic Pump
3       P004              0.16                 11    Hydraulic Pump
4       P005              0.10                  6  Hydraulic Filter

In [13]:
promotions = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\promotions.csv.txt")
promotions.head()

  product_id promotion_active  discount_percent promotion_type
0       P001              Yes                10       Seasonal
1       P002              Yes                15       Seasonal
2       P003               No                 0            NaN
3       P004              Yes                20         Launch
4       P005               No                 0            NaN

In [14]:
launch_curves = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\launch_curves.csv.txt")
launch_curves.head()

,product_id,month_1_demand,month_2_demand,month_3_demand,month_4_demand,month_5_demand,month_6_demand
0,P001,20,35,50,65,80,90
1,P002,22,38,54,70,84,95
2,P003,21,36,52,67,82,92
3,P004,25,42,60,78,95,110
4,P005,18,30,44,58,70,80

In [18]:
failures = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\failures.csv.txt")
failures.head()

  product_id  avg_failure_rate  critical_failures common_spare_part
0       P001              0.12                  8    Hydraulic Pump
1       P002              0.14                  9    Hydraulic Pump
2       P003              0.13                  8    Hydraulic Pump
3       P004              0.16                 11    Hydraulic Pump
4       P005              0.10                  6  Hydraulic Filter

In [19]:
data = products.merge(failures, on="product_id")
data = data.merge(promotions, on="product_id")
data = data.merge(launch_curves, on="product_id")

data.head()

,product_id,avg_failure_rate_x,critical_failures_x,common_spare_part_x,avg_failure_rate_y,critical_failures_y,common_spare_part_y,promotion_active,discount_percent,promotion_type,month_1_demand,month_2_demand,month_3_demand,month_4_demand,month_5_demand,month_6_demand
0,P001,0.12,8,Hydraulic Pump,0.12,8,Hydraulic Pump,Yes,10,Seasonal,20,35,50,65,80,90
1,P002,0.14,9,Hydraulic Pump,0.14,9,Hydraulic Pump,Yes,15,Seasonal,22,38,54,70,84,95
2,P003,0.13,8,Hydraulic Pump,0.13,8,Hydraulic Pump,No,0,NaN,21,36,52,67,82,92
3,P004,0.16,11,Hydraulic Pump,0.16,11,Hydraulic Pump,Yes,20,Launch,25,42,60,78,95,110
4,P005,0.10,6,Hydraulic Filter,0.10,6,Hydraulic Filter,No,0,NaN,18,30,44,58,70,80

In [20]:
data.shape

(30, 16)

In [21]:
data.isnull().sum()

product_id              0
avg_failure_rate_x      0
critical_failures_x     0
common_spare_part_x     0
avg_failure_rate_y      0
critical_failures_y     0
common_spare_part_y     0
promotion_active        0
discount_percent        0
promotion_type         12
month_1_demand          0
month_2_demand          0
month_3_demand          0
month_4_demand          0
month_5_demand          0
month_6_demand          0
dtype: int64

In [22]:
data["promotion_type"] = data["promotion_type"].fillna("None")
data.isnull().sum()

product_id             0
avg_failure_rate_x     0
critical_failures_x    0
common_spare_part_x    0
avg_failure_rate_y     0
critical_failures_y    0
common_spare_part_y    0
promotion_active       0
discount_percent       0
promotion_type         0
month_1_demand         0
month_2_demand         0
month_3_demand         0
month_4_demand         0
month_5_demand         0
month_6_demand         0
dtype: int64

In [23]:
data["product_id"].duplicated().sum()

0

In [24]:
data.columns

Index(['product_id', 'avg_failure_rate_x', 'critical_failures_x',
       'common_spare_part_x', 'avg_failure_rate_y', 'critical_failures_y',
       'common_spare_part_y', 'promotion_active', 'discount_percent',
       'promotion_type', 'month_1_demand', 'month_2_demand', 'month_3_demand',
       'month_4_demand', 'month_5_demand', 'month_6_demand'],
      dtype='object')

In [25]:
data = products.merge(failures, on="product_id")
data = data.merge(promotions, on="product_id")
data = data.merge(launch_curves, on="product_id")

data.columns

Index(['product_id', 'avg_failure_rate_x', 'critical_failures_x',
       'common_spare_part_x', 'avg_failure_rate_y', 'critical_failures_y',
       'common_spare_part_y', 'promotion_active', 'discount_percent',
       'promotion_type', 'month_1_demand', 'month_2_demand', 'month_3_demand',
       'month_4_demand', 'month_5_demand', 'month_6_demand'],
      dtype='object')

In [27]:
failures = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\failures.csv.txt")
promotions = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\promotions.csv.txt")
launch_curves = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\launch_curves.csv.txt")

print(failures.shape)
print(promotions.shape)
print(launch_curves.shape)

(30, 4)
(30, 4)
(30, 7)

In [28]:
data = products.merge(failures, on="product_id")
data = data.merge(promotions, on="product_id")
data = data.merge(launch_curves, on="product_id")

data.shape

(30, 16)

In [29]:
data.columns

Index(['product_id', 'avg_failure_rate_x', 'critical_failures_x',
       'common_spare_part_x', 'avg_failure_rate_y', 'critical_failures_y',
       'common_spare_part_y', 'promotion_active', 'discount_percent',
       'promotion_type', 'month_1_demand', 'month_2_demand', 'month_3_demand',
       'month_4_demand', 'month_5_demand', 'month_6_demand'],
      dtype='object')

In [30]:
products = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\products.csv.txt")
failures = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\failures.csv.txt")
promotions = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\promotions.csv.txt")
launch_curves = pd.read_csv(r"D:\COE PROJECT\spare_parts_analogue_selector\data\launch_curves.csv.txt")

print(products.columns)
print(failures.columns)
print(promotions.columns)
print(launch_curves.columns)

Index(['product_id', 'category', 'engine_power_kw', 'weight_kg', 'price_usd',
       'launch_month'],
      dtype='object')
Index(['product_id', 'avg_failure_rate', 'critical_failures',
       'common_spare_part'],
      dtype='object')
Index(['product_id', 'promotion_active', 'discount_percent', 'promotion_type'], dtype='object')
Index(['product_id', 'month_1_demand', 'month_2_demand', 'month_3_demand',
       'month_4_demand', 'month_5_demand', 'month_6_demand'],
      dtype='object')

In [31]:
data = products.merge(failures, on="product_id", how="inner")
data = data.merge(promotions, on="product_id", how="inner")
data = data.merge(launch_curves, on="product_id", how="inner")

data.shape

(30, 18)

In [32]:
data.columns

Index(['product_id', 'category', 'engine_power_kw', 'weight_kg', 'price_usd',
       'launch_month', 'avg_failure_rate', 'critical_failures',
       'common_spare_part', 'promotion_active', 'discount_percent',
       'promotion_type', 'month_1_demand', 'month_2_demand', 'month_3_demand',
       'month_4_demand', 'month_5_demand', 'month_6_demand'],
      dtype='object')

In [33]:
from sklearn.preprocessing import MinMaxScaler

attribute_columns = ["engine_power_kw", "weight_kg", "price_usd"]

scaler = MinMaxScaler()

data[["engine_power_score", "weight_score", "price_score"]] = scaler.fit_transform(data[attribute_columns])

data[["product_id", "engine_power_score", "weight_score", "price_score"]].head()

  product_id  engine_power_score  weight_score  price_score
0       P001            0.157895      0.148936     0.117647
1       P002            0.263158      0.191489     0.176471
2       P003            0.210526      0.170213     0.147059
3       P004            0.368421      0.255319     0.274510
4       P005            0.105263      0.106383     0.058824

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

attribute_matrix = data[["engine_power_score", "weight_score", "price_score"]]

attribute_similarity = cosine_similarity(attribute_matrix)

attribute_similarity[:5, :5]

array([[1.        , 0.99375995, 0.99775188, 0.99016605, 0.9920577 ],
       [0.99375995, 1.        , 0.99900085, 0.99841608, 0.98185901],
       [0.99775188, 0.99900085, 1.        , 0.99660921, 0.9874192 ],
       [0.99016605, 0.99841608, 0.99660921, 1.        , 0.97123242],
       [0.9920577 , 0.98185901, 0.9874192 , 0.97123242, 1.        ]])

In [35]:
data["category_score"] = data["category"].map(data["category"].value_counts(normalize=True))

data[["product_id", "category", "category_score"]].head()

  product_id   category  category_score
0       P001  Excavator        0.266667
1       P002  Excavator        0.266667
2       P003  Excavator        0.266667
3       P004  Excavator        0.266667
4       P005  Excavator        0.266667

In [36]:
category_similarity = (data["category"].values[:, None] == data["category"].values[None, :]).astype(float)

category_similarity[:5, :5]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
failure_columns = ["avg_failure_rate", "critical_failures"]

failure_scaler = MinMaxScaler()

data[["failure_rate_score", "critical_failure_score"]] = failure_scaler.fit_transform(data[failure_columns])

data[["product_id", "failure_rate_score", "critical_failure_score"]].head()

  product_id  failure_rate_score  critical_failure_score
0       P001            0.333333                0.384615
1       P002            0.466667                0.461538
2       P003            0.400000                0.384615
3       P004            0.600000                0.615385
4       P005            0.200000                0.230769

In [39]:
failure_matrix = data[["failure_rate_score", "critical_failure_score"]]

failure_similarity = cosine_similarity(failure_matrix)

failure_similarity[:5, :5]

array([[1.        , 0.99704985, 0.99587028, 0.99828059, 1.        ],
       [0.99704985, 1.        , 0.99990087, 0.99983471, 0.99704985],
       [0.99587028, 0.99990087, 1.        , 0.9994796 , 0.99587028],
       [0.99828059, 0.99983471, 0.9994796 , 1.        , 0.99828059],
       [1.        , 0.99704985, 0.99587028, 0.99828059, 1.        ]])

In [40]:
launch_columns = [
    "month_1_demand",
    "month_2_demand",
    "month_3_demand",
    "month_4_demand",
    "month_5_demand",
    "month_6_demand"
]

launch_scaler = MinMaxScaler()

launch_scores = launch_scaler.fit_transform(data[launch_columns])

launch_similarity = cosine_similarity(launch_scores)

launch_similarity[:5, :5]

array([[1.        , 0.99907566, 0.9996585 , 0.99928767, 0.99651368],
       [0.99907566, 1.        , 0.99960711, 0.99870941, 0.99654441],
       [0.9996585 , 0.99960711, 1.        , 0.99921886, 0.99730601],
       [0.99928767, 0.99870941, 0.99921886, 1.        , 0.99765129],
       [0.99651368, 0.99654441, 0.99730601, 0.99765129, 1.        ]])

In [41]:
promotion_similarity = (
    data["promotion_active"].values[:, None] ==
    data["promotion_active"].values[None, :]
).astype(float)

promotion_similarity[:5, :5]

array([[1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1.]])

In [42]:
overall_similarity = (
    0.30 * attribute_similarity +
    0.25 * launch_similarity +
    0.20 * category_similarity +
    0.15 * failure_similarity +
    0.10 * promotion_similarity
)

overall_similarity[:5, :5]

array([[1.        , 0.99745438, 0.89862073, 0.99661382, 0.89674573],
       [0.99745438, 1.        , 0.89958716, 0.99917738, 0.89325128],
       [0.89862073, 0.89958716, 1.        , 0.89870942, 0.9949328 ],
       [0.99661382, 0.99917738, 0.89870942, 1.        , 0.89052464],
       [0.89674573, 0.89325128, 0.9949328 , 0.89052464, 1.        ]])

In [43]:
def find_analogue(product_id):
    index = data.index[data["product_id"] == product_id][0]
    scores = overall_similarity[index].copy()
    scores[index] = -1
    best_index = scores.argmax()

    return {
        "target_product": product_id,
        "analogue_product": data.iloc[best_index]["product_id"],
        "similarity_score": round(scores[best_index] * 100, 2)
    }

In [44]:
find_analogue("P001")

{'target_product': 'P001',
 'analogue_product': 'P021',
 'similarity_score': 99.76}

In [45]:
target_index = data.index[data["product_id"] == "P001"][0]
analogue_index = data.index[data["product_id"] == "P021"][0]

print("Product attribute similarity:", round(attribute_similarity[target_index, analogue_index] * 100, 2))
print("Launch curve similarity:", round(launch_similarity[target_index, analogue_index] * 100, 2))
print("Category similarity:", round(category_similarity[target_index, analogue_index] * 100, 2))
print("Failure behaviour similarity:", round(failure_similarity[target_index, analogue_index] * 100, 2))
print("Promotion similarity:", round(promotion_similarity[target_index, analogue_index] * 100, 2))
print("Overall similarity:", round(overall_similarity[target_index, analogue_index] * 100, 2))

Product attribute similarity: 99.49
Launch curve similarity: 99.89
Category similarity: 100.0
Failure behaviour similarity: 99.59
Promotion similarity: 100.0
Overall similarity: 99.76

In [46]:
def get_confidence(similarity_score):
    if similarity_score >= 80:
        return "HIGH"
    elif similarity_score >= 60:
        return "MEDIUM"
    else:
        return "LOW"

get_confidence(99.76)

'HIGH'

In [47]:
def explain_analogue(product_id):
    index = data.index[data["product_id"] == product_id][0]
    scores = overall_similarity[index].copy()
    scores[index] = -1
    best_index = scores.argmax()

    similarity_score = scores[best_index] * 100
    confidence = get_confidence(similarity_score)

    return {
        "Target Product": product_id,
        "Best Analogue": data.iloc[best_index]["product_id"],
        "Product Attribute Similarity": round(attribute_similarity[index, best_index] * 100, 2),
        "Launch Curve Similarity": round(launch_similarity[index, best_index] * 100, 2),
        "Category Similarity": round(category_similarity[index, best_index] * 100, 2),
        "Failure Behaviour Similarity": round(failure_similarity[index, best_index] * 100, 2),
        "Promotion Similarity": round(promotion_similarity[index, best_index] * 100, 2),
        "Overall Similarity": round(similarity_score, 2),
        "Confidence": confidence
    }

In [48]:
explain_analogue("P001")

{'Target Product': 'P001',
 'Best Analogue': 'P021',
 'Product Attribute Similarity': 99.49,
 'Launch Curve Similarity': 99.89,
 'Category Similarity': 100.0,
 'Failure Behaviour Similarity': 99.59,
 'Promotion Similarity': 100.0,
 'Overall Similarity': 99.76,
 'Confidence': 'HIGH'}

In [49]:
explain_analogue("P015")

{'Target Product': 'P015',
 'Best Analogue': 'P013',
 'Product Attribute Similarity': 99.83,
 'Launch Curve Similarity': 99.98,
 'Category Similarity': 100.0,
 'Failure Behaviour Similarity': 99.98,
 'Promotion Similarity': 100.0,
 'Overall Similarity': 99.94,
 'Confidence': 'HIGH'}

In [50]:
explain_analogue("P006")

{'Target Product': 'P006',
 'Best Analogue': 'P026',
 'Product Attribute Similarity': 99.84,
 'Launch Curve Similarity': 98.63,
 'Category Similarity': 100.0,
 'Failure Behaviour Similarity': 100.0,
 'Promotion Similarity': 100.0,
 'Overall Similarity': 99.61,
 'Confidence': 'HIGH'}

In [51]:
data.loc[len(data)] = {
    "product_id": "TEST001",
    "category": "Unknown",
    "engine_power_kw": 500,
    "weight_kg": 20000,
    "price_usd": 200000,
    "launch_month": 6,
    "avg_failure_rate": 0.50,
    "critical_failures": 50,
    "common_spare_part": "Unknown",
    "promotion_active": "No",
    "discount_percent": 0,
    "promotion_type": "None",
    "month_1_demand": 5,
    "month_2_demand": 8,
    "month_3_demand": 10,
    "month_4_demand": 12,
    "month_5_demand": 15,
    "month_6_demand": 18
}

data.tail(1)

,product_id,category,engine_power_kw,weight_kg,price_usd,launch_month,avg_failure_rate,critical_failures,common_spare_part,promotion_active,...,month_3_demand,month_4_demand,month_5_demand,month_6_demand,engine_power_score,weight_score,price_score,category_score,failure_rate_score,critical_failure_score
30,TEST001,Unknown,500,20000,200000,6,0.5,50,Unknown,No,...,10,12,15,18,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
test_attributes = data.loc[data["product_id"] == "TEST001", ["engine_power_kw", "weight_kg", "price_usd"]]

test_failure = data.loc[data["product_id"] == "TEST001", ["avg_failure_rate", "critical_failures"]]

test_launch = data.loc[data["product_id"] == "TEST001", launch_columns]

test_attribute_scores = scaler.transform(test_attributes)
test_failure_scores = failure_scaler.transform(test_failure)
test_launch_scores = launch_scaler.transform(test_launch)

print(test_attribute_scores)
print(test_failure_scores)
print(test_launch_scores)

[[4.36842105 3.34042553 3.05882353]]
[[2.86666667 3.61538462]]
[[-0.375      -0.51515152 -0.62790698 -0.65454545 -0.64179104 -0.62820513]]

In [53]:
test_attribute_similarity = cosine_similarity(test_attribute_scores, scaler.transform(data.iloc[:30][attribute_columns]))[0]

test_failure_similarity = cosine_similarity(test_failure_scores, failure_scaler.transform(data.iloc[:30][failure_columns]))[0]

test_launch_similarity = cosine_similarity(test_launch_scores, launch_scaler.transform(data.iloc[:30][launch_columns]))[0]

test_category_similarity = (data.iloc[:30]["category"].values == "Unknown").astype(float)

test_promotion_similarity = (data.iloc[:30]["promotion_active"].values == "No").astype(float)

test_overall_similarity = (
    0.30 * test_attribute_similarity +
    0.25 * test_launch_similarity +
    0.20 * test_category_similarity +
    0.15 * test_failure_similarity +
    0.10 * test_promotion_similarity
)

best_index = test_overall_similarity.argmax()

print("Best analogue:", data.iloc[best_index]["product_id"])
print("Similarity:", round(test_overall_similarity[best_index] * 100, 2))

Best analogue: P003
Similarity: 30.04

In [54]:
test_similarity_score = test_overall_similarity[best_index] * 100

if test_similarity_score >= 80:
    test_confidence = "HIGH"
elif test_similarity_score >= 60:
    test_confidence = "MEDIUM"
else:
    test_confidence = "LOW"

print("Target product: TEST001")
print("Best analogue:", data.iloc[best_index]["product_id"])
print("Similarity:", round(test_similarity_score, 2), "%")
print("Confidence:", test_confidence)

if test_confidence == "LOW":
    print("Warning: No strong analogue found. Manual review required.")

Target product: TEST001
Best analogue: P003
Similarity: 30.04 %
Confidence: LOW
Warning: No strong analogue found. Manual review required.

In [55]:
test_product = data.iloc[0].copy()

test_product["product_id"] = "TEST002"
test_product["category"] = "Excavator"
test_product["engine_power_kw"] = 106
test_product["weight_kg"] = 5120
test_product["price_usd"] = 52000
test_product["avg_failure_rate"] = 0.125
test_product["critical_failures"] = 8
test_product["promotion_active"] = "Yes"
test_product["month_1_demand"] = 21
test_product["month_2_demand"] = 36
test_product["month_3_demand"] = 52
test_product["month_4_demand"] = 67
test_product["month_5_demand"] = 82
test_product["month_6_demand"] = 93

print(test_product)

product_id                       TEST002
category                       Excavator
engine_power_kw                      106
weight_kg                           5120
price_usd                          52000
launch_month                           1
avg_failure_rate                   0.125
critical_failures                      8
common_spare_part         Hydraulic Pump
promotion_active                     Yes
discount_percent                      10
promotion_type                  Seasonal
month_1_demand                        21
month_2_demand                        36
month_3_demand                        52
month_4_demand                        67
month_5_demand                        82
month_6_demand                        93
engine_power_score              0.157895
weight_score                    0.148936
price_score                     0.117647
category_score                  0.266667
failure_rate_score              0.333333
critical_failure_score          0.384615
Name: 0, dtype: object

In [56]:
test2_attributes = test_product[attribute_columns].to_frame().T
test2_failure = test_product[failure_columns].to_frame().T
test2_launch = test_product[launch_columns].to_frame().T

test2_attribute_scores = scaler.transform(test2_attributes)
test2_failure_scores = failure_scaler.transform(test2_failure)
test2_launch_scores = launch_scaler.transform(test2_launch)

test2_attribute_similarity = cosine_similarity(
    test2_attribute_scores,
    scaler.transform(data.iloc[:30][attribute_columns])
)[0]

test2_failure_similarity = cosine_similarity(
    test2_failure_scores,
    failure_scaler.transform(data.iloc[:30][failure_columns])
)[0]

test2_launch_similarity = cosine_similarity(
    test2_launch_scores,
    launch_scaler.transform(data.iloc[:30][launch_columns])
)[0]

test2_category_similarity = (
    data.iloc[:30]["category"].values == test_product["category"]
).astype(float)

test2_promotion_similarity = (
    data.iloc[:30]["promotion_active"].values == test_product["promotion_active"]
).astype(float)

test2_overall_similarity = (
    0.30 * test2_attribute_similarity +
    0.25 * test2_launch_similarity +
    0.20 * test2_category_similarity +
    0.15 * test2_failure_similarity +
    0.10 * test2_promotion_similarity
)

top_indices = test2_overall_similarity.argsort()[-5:][::-1]

for index in top_indices:
    print(
        data.iloc[index]["product_id"],
        round(test2_overall_similarity[index] * 100, 2), "%"
    )

P021 99.96 %
P002 99.96 %
P004 99.92 %
P029 99.89 %
P001 99.88 %

In [57]:
top_score = test2_overall_similarity[top_indices[0]] * 100
second_score = test2_overall_similarity[top_indices[1]] * 100

difference = abs(top_score - second_score)

print("Best analogue:", data.iloc[top_indices[0]]["product_id"])
print("Best similarity:", round(top_score, 2), "%")
print("Second analogue:", data.iloc[top_indices[1]]["product_id"])
print("Second similarity:", round(second_score, 2), "%")
print("Difference:", round(difference, 2), "%")

if difference <= 1:
    print("Confidence: MEDIUM")
    print("Warning: Multiple near-tied analogues found. Manual review recommended.")
else:
    print("Confidence: HIGH")

Best analogue: P021
Best similarity: 99.96 %
Second analogue: P002
Second similarity: 99.96 %
Difference: 0.0 %
Confidence: MEDIUM
Warning: Multiple near-tied analogues found. Manual review recommended.

In [58]:
test3_product = data.iloc[0].copy()

test3_product["product_id"] = "TEST003"
test3_product["promotion_active"] = None
test3_product["discount_percent"] = None
test3_product["promotion_type"] = None

print(test3_product[[
    "product_id",
    "category",
    "engine_power_kw",
    "weight_kg",
    "price_usd",
    "promotion_active",
    "discount_percent",
    "promotion_type"
]])

product_id            TEST003
category            Excavator
engine_power_kw           100
weight_kg                5000
price_usd               50000
promotion_active         None
discount_percent         None
promotion_type           None
Name: 0, dtype: object

In [59]:
test3_promotion_similarity = (
    data.iloc[:30]["promotion_active"].values == test3_product["promotion_active"]
).astype(float)

print(test3_promotion_similarity)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

In [60]:
test3_attribute_scores = scaler.transform(
    test3_product[attribute_columns].to_frame().T
)

test3_failure_scores = failure_scaler.transform(
    test3_product[failure_columns].to_frame().T
)

test3_launch_scores = launch_scaler.transform(
    test3_product[launch_columns].to_frame().T
)

test3_attribute_similarity = cosine_similarity(
    test3_attribute_scores,
    scaler.transform(data.iloc[:30][attribute_columns])
)[0]

test3_failure_similarity = cosine_similarity(
    test3_failure_scores,
    failure_scaler.transform(data.iloc[:30][failure_columns])
)[0]

test3_launch_similarity = cosine_similarity(
    test3_launch_scores,
    launch_scaler.transform(data.iloc[:30][launch_columns])
)[0]

test3_category_similarity = (
    data.iloc[:30]["category"].values == test3_product["category"]
).astype(float)

test3_overall_similarity = (
    0.30 * test3_attribute_similarity +
    0.25 * test3_launch_similarity +
    0.20 * test3_category_similarity +
    0.15 * test3_failure_similarity
) / 0.90

best_index = test3_overall_similarity.argmax()

print("Best analogue:", data.iloc[best_index]["product_id"])
print("Similarity:", round(test3_overall_similarity[best_index] * 100, 2), "%")
print("Promotion information: Missing")
print("Confidence should be reduced because promotion information is unavailable.")

Best analogue: P001
Similarity: 100.0 %
Promotion information: Missing
Confidence should be reduced because promotion information is unavailable.